- fetch:
    src: "{{ ssh_dir }}/id_rsa"
    dest: ~/.fetch/{{ user_account }}
    validate_checksum: yes

- debug: 
    msg: "/.fetch/{{ user_account }}"

- name: setup credential 0600
  delegate_to: localhost
  file:
    path: "{{ user_credential }}"
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: sshkey test
  local_action: shell ssh {{ user_account }}@{{ ansible_host }} -i {{ user_credential }} "echo success"