---

- hosts: stage2
  become: true
  become_user: root
  tasks:
#user_account & user_group在執行腳本時代入變數
    - name: Create user 'user_account'
      user:
        name: user_account
        comment: user_account

    - name: Set authorized key taken from file
      authorized_key:
        user: user_account
        state: present
        key: "{{ lookup('file', '.pubkey/user_account.pub') }}"

    - name: Add 'user_account' to ssh AllowUsers
      replace:
        backup: yes
        path: /etc/ssh/sshd_config
        regexp: '^(AllowUsers(?!.*\b user_account\b).*)$'
        replace: '\1 user_account'

    - name: Reload service sshd
      systemd:
        name: sshd
        state: reloaded
        
    - name: Add 'user_account' to sudo group
      replace:
        backup: yes
        path: /etc/sudoers.d/user_group
        regexp: '^(User_Alias OPTSR=(?!.*user_account).*)$' #比對user_account前後不管
        replace: '\1, user_account' #前方要插入逗點: user1, user2, ...
