---

- hosts: optsr
  become: true
  become_user: root
  tasks:

    - name: Create user 'optsr1'
      user:
        name: optsr1
        comment: optsr1

    - name: Set authorized key taken from file
      authorized_key:
        user: optsr1
        state: present
        key: "{{ lookup('file', '.pubkey/opt/optsr1.pub') }}"

    - name: Allow 'optsr1' sudo permission 
      lineinfile:
        path: /etc/sudoers
        line: 'optsr1 ALL=(ALL) NOPASSWD: ALL'
        create: yes

    - name: Add 'optsr1' to ssh AllowUsers
      replace:
        backup: yes
        path: /etc/ssh/sshd_config
        regexp: '^(AllowUsers(?!.*\b optsr1\b).*)$'
        replace: '\1 optsr1'

    - name: Reload service sshd
      systemd:
        name: sshd
        state: reloaded
